version: "3.9"

services:
  ussd-api:
    image: node:20-bullseye
    container_name: ussd-api
    working_dir: /app
    restart: unless-stopped

    command: sh -c "npm install --omit=dev && node src/bootstrap/server.js"

    volumes:
      - ./:/app

    expose :
      - "3000"

    env_file:
      - .env

    depends_on:
      - redis

    networks:
      - dokploy-network

  redis:
    image: redis:7-alpine
    container_name: ussd-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no"]

    expose :
      - "6379"

    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true  # Use the previously created shared network