version: "3.9"

services:

  ussd-redis:
    image: redis:7-alpine
    container_name: ussd-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no"]
    expose:
      - "6379"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: bridge