version: "3.9"

services:
  api:
    image: node:20-alpine
    container_name: express-api
    working_dir: /app
    volumes:
      - .:/app
    expose :
      - "3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    command: sh -c "npm install && node src/index.js"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true  # Use the previously created shared network