version: "3.9"

services:
  ussd_service_default:
    image: node:20-bullseye
    container_name: ussd_service_default
    working_dir: /app
    restart: unless-stopped

    command: sh -c "npm install --omit=dev && node src/bootstrap/server.js"

    volumes:
      - ./:/app

    expose :
      - "3000"

    env_file:
      - .env

    depends_on:
      - ussd-redis

    networks:
      - dokploy-network

  ussd-redis:
    image: redis:7-alpine
    container_name: ussd-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no"]

    expose :
      - "6379"

    networks:
      - dokploy-network
  
  ussd-postgres:
    image: postgres:16-alpine
    container_name: ussd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ussd
      POSTGRES_PASSWORD: ussd
      POSTGRES_DB: ussd
    ports:
      - "5432:5432"
    networks:
      - dokploy-network
    volumes:
      - /var/containers/volumes/prod/pgdata:/var/lib/postgresql/data


networks:
  dokploy-network:
    external: true  # Use the previously created shared network